// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using privoda.Models;

namespace privoda.Migrations
{
    [DbContext(typeof(PrivodaDbContext))]
    partial class PrivodaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("privoda.Models.CircuitBreaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AFrom");

                    b.Property<double>("ATo");

                    b.Property<bool>("FirstTypeCoordination");

                    b.Property<string>("Reference");

                    b.Property<bool>("SecondTypeCoordination");

                    b.HasKey("Id");

                    b.ToTable("CircuitBreakers");
                });

            modelBuilder.Entity("privoda.Models.Coil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentTypeId");

                    b.Property<string>("Reference");

                    b.Property<int>("Voltage");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTypeId");

                    b.ToTable("Coils");
                });

            modelBuilder.Entity("privoda.Models.Contactor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AFrom");

                    b.Property<double>("ATo");

                    b.Property<bool>("FirstTypeCoordination");

                    b.Property<string>("Reference");

                    b.Property<bool>("SecondTypeCoordination");

                    b.HasKey("Id");

                    b.ToTable("Contactors");
                });

            modelBuilder.Entity("privoda.Models.CurrentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("CurrentTypes");
                });

            modelBuilder.Entity("privoda.Models.Description", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Areas");

                    b.Property<string>("Average");

                    b.Property<string>("Big");

                    b.Property<int>("LineId");

                    b.Property<string>("Small");

                    b.HasKey("Id");

                    b.ToTable("Descriptions");
                });

            modelBuilder.Entity("privoda.Models.LineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LineTypes");
                });

            modelBuilder.Entity("privoda.Models.ModelLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image");

                    b.Property<string>("Name");

                    b.Property<int>("TypeId");

                    b.Property<string>("Video");

                    b.HasKey("Id");

                    b.ToTable("ModelLines");
                });

            modelBuilder.Entity("privoda.Models.PowerAndCurrent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Current");

                    b.Property<double>("Power");

                    b.HasKey("Id");

                    b.ToTable("PowerAndCurrent");
                });

            modelBuilder.Entity("privoda.Models.Coil", b =>
                {
                    b.HasOne("privoda.Models.CurrentType", "СurrentType")
                        .WithMany()
                        .HasForeignKey("CurrentTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
